#
# SocketTestMaster — minimal RS485Socket master example
#
[platformio]
lib_dir = /Users/amp/Dropbox/Arduino/libraries
src_dir = ../../../../../libraries/RS485Utils/examples/SocketTest/SocketTestMaster

[env:esp32]
platform = espressif32
framework = arduino
board = esp32doit-devkit-v1
build_flags =
    -DDEBUG_LEVEL=1
    -DRS485_HARDWARE_SERIAL=2
    -DPIN_RS485_RECV=16
    -DPIN_RS485_XMIT=17
    -DPIN_RS485_ENABLED=18

[env:nano]
platform = atmelavr
framework = arduino
board = nanoatmega328
build_flags = -DDEBUG_LEVEL=1
